# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='map_url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='locationtype',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
