# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navui', '0002_auto_20160416_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='map_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
