# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navui', '0003_auto_20160416_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='locationtype',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
