# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navui', '0005_navigationaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='display_seconds',
            field=models.IntegerField(default=30),
        ),
    ]
