# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navui', '0006_location_display_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
