# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navui', '0007_location_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='btn_class',
            field=models.CharField(default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='location',
            name='btn_icon',
            field=models.CharField(default='', max_length=20),
        ),
    ]
