# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navui', '0008_auto_20160416_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='btn_icon',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
